### ISSUE TITLE
Create a backup script for all dot-files

### ISSUE THREAD

**Issue by jacquelineMorin** [lightblueseas/linuxstuff#5]
Create a backup script for all dot-files like “.profile”,  “.bash_profile” and so on.

**Comment by jimmyMaci** [comment]
Do you mean that the script shell make a union of all script files and write it back to file or insert the result in an existing ".profile" or ".zshrc"?

**Comment by jimmyMaci** [comment]
I created two scripts that merges the needed files. I hope this can close this issue @jacquelineMorin.

**Comment by jacquelineMorin** [comment]
Thanks, yes thats what i meant.
