### ISSUE TITLE
Best config of clipit

### ISSUE THREAD

**Issue by tatjana19** [lightblueseas/linuxstuff#6]
Hi there, can anybody tell me whats the best config with clipit. In the [wiki](https://github.com/lightblueseas/linuxstuff/wiki/Initial-install-of-ubuntu-os) is descripted how to install but i didnt find a description how to config.

Cheers, Tatjana

**Comment by jimmyMaci** [comment]
Hi Tatjana19 i do not know if this is the best configuration but i can show you how i have config it.:

![auswahl_011](https://user-images.githubusercontent.com/9551071/32414426-90bab532-c226-11e7-852f-61c020666f30.png)
 
and for the history:

![auswahl_012](https://user-images.githubusercontent.com/9551071/32414434-e0367e98-c226-11e7-973c-3ee7e01b7221.png)

and shortcuts:

![auswahl_013](https://user-images.githubusercontent.com/9551071/32414435-edec1a8e-c226-11e7-9b04-1a7212c27a73.png)

for me this is the best config, but you can tell me if you find a better one.

**Comment by tatjana19** [comment]
Thanks @jimmyMaci i think this should work
