### ISSUE TITLE
Import of jautodoc config files

### ISSUE THREAD

**Issue by jacquelineMorin** [lightblueseas/linuxstuff#7]
Hello guys,

there are some jautodoc config files in path /linuxstuff/src/main/resources/eclipse/config/jautodoc.

Can somebody explain how to import them and where?

**Comment by astrapi69** [comment]
Hey Jacqueline, you can import the jautodoc config files by going in eclipse Window->Preferences->Java->Jautodoc
![auswahl_021](https://user-images.githubusercontent.com/1822320/37243852-7dcfbf64-2480-11e8-87b0-f2ad12d85f87.png)

- For import the file 'jautodoc_replacements.xml' use the 'Import...'-Button.

- For import the file 'jautodoc_preferences.xml' use the 'Import All...'-Button.

- For import the file 'jautodoc_templates.xml' you have to go Window->Preferences->Java->Jautodoc->Templates and use the 'Import...'-Button.

- Last but not least for import the file 'codetemplates.xml' you have to go Window->Preferences->Java->Code Style->Code Templates and use the 'Import...'-Button.

Cheers
